### ISSUE TITLE
Measure and show code coverage

### ISSUE THREAD

**Issue by domi41** [MieuxVoter/majority-judgment-library-java#13]
Coveralls, perhaps?

With https://github.com/trautonen/coveralls-maven-plugin ?

**Comment by domi41** [comment]
I'm dropping this for now ; if anyone wants to try this out, they're more than welcome.

Keep in mind that our constraint is to be compatible Java 8.

**Comment by jeanpic** [comment]
I can help with this. I forked the project and modified the workflow to create the JaCoCo report and analyze the code with sonarcloud. Tell me what you think : #14
